import { email } from "zod";
import { hashSync } from "bcrypt-ts-edge";

const sampleData = {
  users: [
    {
      name: "Ali",
      email: "admin@example.com",
      password: hashSync("123456", 10),
      role: "admin",
    },
    {
      name: "Ahmed",
      email: "user@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
    {
      name: "Sara Khalid",
      email: "sara.khalid@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
    {
      name: "Omar Naser",
      email: "omar.naser@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
    {
      name: "Layla Hassan",
      email: "layla.hassan@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
    {
      name: "Yousef Ibrahim",
      email: "yousef.ibrahim@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
    {
      name: "Noor Al-Fadhli",
      email: "noor.alfadhli@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
    {
      name: "Mariam Saeed",
      email: "mariam.saeed@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
    {
      name: "Khalid Rashid",
      email: "khalid.rashid@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
    {
      name: "Fatima Zayed",
      email: "fatima.zayed@example.com",
      password: hashSync("123456", 10),
      role: "user",
    },
  ],
  products: [
    {
      name: "Polo Sporting Stretch Shirt",
      nameAr: "قميص بولو سبورتينج سترتش",
      slug: "polo-sporting-stretch-shirt",
      category: "Fashion",
      categoryAr: "أزياء",
      description: "Classic Polo style with modern comfort",
      descriptionAr: "ستايل بولو الكلاسيكي مع راحة عصرية",
      images: [
        "/images/sample-products/p1-1.jpg",
        "/images/sample-products/p1-2.jpg",
      ],
      price: 59.99,
      brand: "Polo",
      brandAr: "بولو",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
    },
    {
      name: "Brooks Brothers Long Sleeved Shirt",
      nameAr: "قميص بروكس براذرز بأكمام طويلة",
      slug: "brooks-brothers-long-sleeved-shirt",
      category: "Fashion",
      categoryAr: "أزياء",
      description: "Timeless style and premium comfort",
      descriptionAr: "أناقة خالدة وراحة فائقة",
      images: [
        "/images/sample-products/p2-1.jpg",
        "/images/sample-products/p2-2.jpg",
      ],
      price: 85.9,
      brand: "Brooks Brothers",
      brandAr: "بروكس براذرز",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "banner-2.jpg",
    },
    {
      name: "Tommy Hilfiger Classic Fit Dress Shirt",
      nameAr: "قميص تومي هيلفيغر كلاسيك فيت",
      slug: "tommy-hilfiger-classic-fit-dress-shirt",
      category: "Fashion",
      categoryAr: "أزياء",
      description: "A perfect blend of sophistication and comfort",
      descriptionAr: "مزيج مثالي بين الرقي والراحة",
      images: [
        "/images/sample-products/p3-1.jpg",
        "/images/sample-products/p3-2.jpg",
      ],
      price: 99.95,
      brand: "Tommy Hilfiger",
      brandAr: "تومي هيلفيغر",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Calvin Klein Slim Fit Stretch Shirt",
      nameAr: "قميص كالفن كلاين سليم فيت سترتش",
      slug: "calvin-klein-slim-fit-stretch-shirt",
      category: "Fashion",
      categoryAr: "أزياء",
      description: "Streamlined design with flexible stretch fabric",
      descriptionAr: "تصميم انسيابي مع نسيج مرن ومريح",
      images: [
        "/images/sample-products/p4-1.jpg",
        "/images/sample-products/p4-2.jpg",
      ],
      price: 39.95,
      brand: "Calvin Klein",
      brandAr: "كالفن كلاين",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Polo Ralph Lauren Oxford Shirt",
      nameAr: "قميص بولو رالف لورين أكسفورد",
      slug: "polo-ralph-lauren-oxford-shirt",
      category: "Fashion",
      categoryAr: "أزياء",
      description: "Iconic Polo design with refined oxford fabric",
      descriptionAr: "تصميم بولو الشهير بنسيج أكسفورد الراقي",
      images: [
        "/images/sample-products/p5-1.jpg",
        "/images/sample-products/p5-2.jpg",
      ],
      price: 79.99,
      brand: "Polo",
      brandAr: "بولو",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Polo Classic Pink Hoodie",
      nameAr: "هودي بولو كلاسيك وردي",
      slug: "polo-classic-pink-hoodie",
      category: "Fashion",
      categoryAr: "أزياء",
      description: "Soft, stylish, and perfect for laid-back days",
      descriptionAr: "ناعم، أنيق، ومثالي للأيام المريحة",
      images: [
        "/images/sample-products/p6-1.jpg",
        "/images/sample-products/p6-2.jpg",
      ],
      price: 99.99,
      brand: "Polo",
      brandAr: "بولو",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    // Fashion (additional)
    {
      name: "Denim Row Boutique Denim Collection",
      nameAr: "مجموعة دينم رو للجينز",
      slug: "denim-row-boutique-denim-collection",
      category: "Fashion",
      categoryAr: "أزياء",
      description: "Skinny and straight fits from our curated boutique denim wall.",
      descriptionAr: "قصات ضيقة ومستقيمة من مجموعتنا المختارة من الجينز.",
      images: [
        "https://images.unsplash.com/photo-1560243563-062bfc001d68",
        "https://images.unsplash.com/photo-1560243563-062bfc001d68",
      ],
      price: 74.99,
      brand: "Denim Row",
      brandAr: "دينم رو",
      rating: 4.3,
      numReviews: 14,
      stock: 18,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Denim Row Suede Oxford Dress Shoes",
      nameAr: "حذاء دينم رو الأوكسفورد من السويدي",
      slug: "denim-row-suede-oxford-dress-shoes",
      category: "Fashion",
      categoryAr: "أزياء",
      description: "Classic suede oxfords that dress up any smart-casual outfit.",
      descriptionAr: "حذاء أوكسفورد كلاسيكي من السويدي يضفي أناقة على أي إطلالة.",
      images: [
        "https://images.unsplash.com/photo-1560343090-f0409e92791a",
        "https://images.unsplash.com/photo-1560343090-f0409e92791a",
      ],
      price: 89.0,
      brand: "Denim Row",
      brandAr: "دينم رو",
      rating: 4.5,
      numReviews: 7,
      stock: 11,
      isFeatured: false,
      banner: null,
    },
    // Electronics
    {
      name: "Nova Wireless Over-Ear Headphones",
      nameAr: "سماعات نوفا اللاسلكية فوق الأذن",
      slug: "nova-wireless-over-ear-headphones",
      category: "Electronics",
      categoryAr: "إلكترونيات",
      description: "Premium wireless headphones with deep bass and all-day comfort.",
      descriptionAr: "سماعات لاسلكية فاخرة بصوت جهير عميق وراحة طوال اليوم.",
      images: [
        "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
        "https://images.unsplash.com/photo-1524678606370-a47ad25cb82a",
      ],
      price: 129.99,
      brand: "Nova Audio",
      brandAr: "نوفا أوديو",
      rating: 4.6,
      numReviews: 24,
      stock: 15,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Pulse Smart Fitness Watch",
      nameAr: "ساعة بالس الذكية الرياضية",
      slug: "pulse-smart-fitness-watch",
      category: "Electronics",
      categoryAr: "إلكترونيات",
      description: "Track your workouts, heart rate, and sleep with this sleek smartwatch.",
      descriptionAr: "تتبع تمارينك ومعدل ضربات قلبك ونومك بهذه الساعة الذكية الأنيقة.",
      images: [
        "https://images.unsplash.com/photo-1546868871-7041f2a55e12",
        "https://images.unsplash.com/photo-1553545204-4f7d339aa06a",
      ],
      price: 179.0,
      brand: "Pulse Tech",
      brandAr: "بالس تك",
      rating: 4.4,
      numReviews: 31,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Glide Wireless Keyboard & Mouse Combo",
      nameAr: "طقم لوحة مفاتيح وماوس لاسلكي جلايد",
      slug: "glide-wireless-keyboard-mouse-combo",
      category: "Electronics",
      categoryAr: "إلكترونيات",
      description: "A slim, responsive keyboard and mouse duo for home and office.",
      descriptionAr: "طقم لوحة مفاتيح وماوس رفيع وسريع الاستجابة للمنزل والمكتب.",
      images: [
        "https://images.unsplash.com/photo-1587829741301-dc798b83add3",
        "https://images.unsplash.com/photo-1587829741301-dc798b83add3",
      ],
      price: 59.5,
      brand: "Glide",
      brandAr: "جلايد",
      rating: 4.2,
      numReviews: 9,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    // Home & Kitchen
    {
      name: "Elm Modern Accent Armchair",
      nameAr: "كرسي إلم العصري",
      slug: "elm-modern-accent-armchair",
      category: "Home & Kitchen",
      categoryAr: "المنزل والمطبخ",
      description: "A statement armchair that brings warmth and comfort to any living room.",
      descriptionAr: "كرسي مميز يضفي الدفء والراحة على غرفة المعيشة.",
      images: [
        "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
        "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6",
      ],
      price: 249.0,
      brand: "Elm Home",
      brandAr: "إلم هوم",
      rating: 4.7,
      numReviews: 19,
      stock: 6,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Hearth Chef's Cookware Set",
      nameAr: "طقم أواني هيرث للطهي",
      slug: "hearth-chefs-cookware-set",
      category: "Home & Kitchen",
      categoryAr: "المنزل والمطبخ",
      description: "A durable non-stick cookware set built for everyday cooking.",
      descriptionAr: "طقم أواني طبخ غير لاصقة ومتينة للاستخدام اليومي.",
      images: [
        "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136",
        "https://images.unsplash.com/photo-1556909212-d5b604d0c90d",
      ],
      price: 139.0,
      brand: "Hearth Kitchen",
      brandAr: "هيرث كيتشن",
      rating: 4.5,
      numReviews: 22,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Nest Cozy Home Decor Set",
      nameAr: "طقم نِست لديكور المنزل الدافئ",
      slug: "nest-cozy-home-decor-set",
      category: "Home & Kitchen",
      categoryAr: "المنزل والمطبخ",
      description: "Curated decor pieces to add a cozy touch to your space.",
      descriptionAr: "قطع ديكور منتقاة بعناية تضفي لمسة دافئة على منزلك.",
      images: [
        "https://images.unsplash.com/photo-1517705008128-361805f42e86",
        "https://images.unsplash.com/photo-1517705008128-361805f42e86",
      ],
      price: 79.0,
      brand: "Nest Living",
      brandAr: "نِست ليفينغ",
      rating: 4.1,
      numReviews: 6,
      stock: 14,
      isFeatured: false,
      banner: null,
    },
    // Beauty
    {
      name: "Lumina Complete Makeup Collection",
      nameAr: "مجموعة لومينا الكاملة للمكياج",
      slug: "lumina-complete-makeup-collection",
      category: "Beauty",
      categoryAr: "الجمال",
      description: "A curated makeup set with everything you need for a flawless look.",
      descriptionAr: "مجموعة مكياج منتقاة تضم كل ما تحتاجينه لإطلالة مثالية.",
      images: [
        "https://images.unsplash.com/photo-1512496015851-a90fb38ba796",
        "https://images.unsplash.com/photo-1512496015851-a90fb38ba796",
      ],
      price: 89.0,
      brand: "Lumina Beauty",
      brandAr: "لومينا بيوتي",
      rating: 4.6,
      numReviews: 28,
      stock: 9,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Silka Nourishing Hair Oil",
      nameAr: "زيت سيلكا المغذي للشعر",
      slug: "silka-nourishing-hair-oil",
      category: "Beauty",
      categoryAr: "الجمال",
      description: "A lightweight oil that nourishes and adds shine to every hair type.",
      descriptionAr: "زيت خفيف يغذي الشعر ويمنحه لمعاناً لجميع أنواع الشعر.",
      images: [
        "https://images.unsplash.com/photo-1526947425960-945c6e72858f",
        "https://images.unsplash.com/photo-1526947425960-945c6e72858f",
      ],
      price: 24.99,
      brand: "Silka",
      brandAr: "سيلكا",
      rating: 4.3,
      numReviews: 17,
      stock: 25,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Dew Everyday Skincare Essentials",
      nameAr: "أساسيات ديو اليومية للعناية بالبشرة",
      slug: "dew-everyday-skincare-essentials",
      category: "Beauty",
      categoryAr: "الجمال",
      description: "Gentle daily essentials to cleanse, hydrate, and protect your skin.",
      descriptionAr: "أساسيات يومية لطيفة لتنظيف البشرة وترطيبها وحمايتها.",
      images: [
        "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9",
        "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9",
      ],
      price: 54.0,
      brand: "Dew Skincare",
      brandAr: "ديو سكين كير",
      rating: 4.4,
      numReviews: 13,
      stock: 16,
      isFeatured: false,
      banner: null,
    },
    // Sports
    {
      name: "Aero Classic Colorblock Sneakers",
      nameAr: "حذاء إيرو الرياضي متعدد الألوان",
      slug: "aero-classic-colorblock-sneakers",
      category: "Sports",
      categoryAr: "رياضة",
      description: "Lightweight sneakers with a bold colorblock design for everyday training.",
      descriptionAr: "حذاء رياضي خفيف بتصميم جريء متعدد الألوان للتمرين اليومي.",
      images: [
        "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a",
        "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519",
      ],
      price: 94.99,
      brand: "Aero Sport",
      brandAr: "إيرو سبورت",
      rating: 4.5,
      numReviews: 21,
      stock: 13,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Aero Performance Running Shoes",
      nameAr: "حذاء إيرو للجري الاحترافي",
      slug: "aero-performance-running-shoes",
      category: "Sports",
      categoryAr: "رياضة",
      description: "Responsive cushioning built for long-distance runners.",
      descriptionAr: "توسيد سريع الاستجابة مصمم لعشاق الجري لمسافات طويلة.",
      images: [
        "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
        "https://images.unsplash.com/photo-1542291026-7eec264c27ff",
      ],
      price: 109.0,
      brand: "Aero Sport",
      brandAr: "إيرو سبورت",
      rating: 4.6,
      numReviews: 16,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Flex Adjustable Dumbbell & Band Set",
      nameAr: "طقم فلكس للدمبل والحزام المطاطي",
      slug: "flex-adjustable-dumbbell-band-set",
      category: "Sports",
      categoryAr: "رياضة",
      description: "A compact home-gym set with adjustable dumbbells and a resistance band.",
      descriptionAr: "طقم صالة رياضية منزلية مدمج يضم دمبل قابل للتعديل وحزام مقاومة.",
      images: [
        "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2",
        "https://images.unsplash.com/photo-1517836357463-d25dfeac3438",
      ],
      price: 64.0,
      brand: "Flex Fitness",
      brandAr: "فلكس فتنس",
      rating: 4.2,
      numReviews: 11,
      stock: 17,
      isFeatured: false,
      banner: null,
    },
    // Gaming
    {
      name: "Arcadia Home Gaming Console Bundle",
      nameAr: "طقم أركاديا لألعاب الفيديو المنزلية",
      slug: "arcadia-home-gaming-console-bundle",
      category: "Gaming",
      categoryAr: "ألعاب",
      description: "Everything you need to set up an immersive home gaming station.",
      descriptionAr: "كل ما تحتاجه لإعداد محطة ألعاب منزلية غامرة.",
      images: [
        "https://images.unsplash.com/photo-1593305841991-05c297ba4575",
        "https://images.unsplash.com/photo-1593305841991-05c297ba4575",
      ],
      price: 399.0,
      brand: "Arcadia",
      brandAr: "أركاديا",
      rating: 4.8,
      numReviews: 34,
      stock: 5,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Tabletop Strategy Board Game Night",
      nameAr: "ليلة ألعاب الطاولة الاستراتيجية",
      slug: "tabletop-strategy-board-game-night",
      category: "Gaming",
      categoryAr: "ألعاب",
      description: "A deep strategy board game perfect for family game nights.",
      descriptionAr: "لعبة طاولة استراتيجية ممتعة ومثالية لأمسيات العائلة.",
      images: [
        "https://images.unsplash.com/photo-1585504198199-20277593b94f",
        "https://images.unsplash.com/photo-1585504198199-20277593b94f",
      ],
      price: 44.5,
      brand: "Tabletop Co.",
      brandAr: "تيبل توب",
      rating: 4.3,
      numReviews: 12,
      stock: 22,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Arcadia Gaming Accessories Bundle",
      nameAr: "طقم أركاديا لإكسسوارات الألعاب",
      slug: "arcadia-gaming-accessories-bundle",
      category: "Gaming",
      categoryAr: "ألعاب",
      description: "Controller, charging dock, and essentials bundled for gamers on the go.",
      descriptionAr: "يد تحكم وقاعدة شحن وأساسيات مجمعة للاعبين أينما كانوا.",
      images: [
        "https://images.unsplash.com/photo-1512686096451-a15c19314d59",
        "https://images.unsplash.com/photo-1512686096451-a15c19314d59",
      ],
      price: 79.0,
      brand: "Arcadia",
      brandAr: "أركاديا",
      rating: 4.1,
      numReviews: 8,
      stock: 19,
      isFeatured: false,
      banner: null,
    },
    // Books
    {
      name: "Chapter & Verse Fiction Collection",
      nameAr: "مجموعة تشابتر آند فيرس الأدبية",
      slug: "chapter-verse-fiction-collection",
      category: "Books",
      categoryAr: "كتب",
      description: "A hand-picked bundle of bestselling fiction titles.",
      descriptionAr: "مجموعة منتقاة بعناية من أفضل الروايات مبيعاً.",
      images: [
        "https://images.unsplash.com/photo-1495446815901-a7297e633e8d",
        "https://images.unsplash.com/photo-1512820790803-83ca734da794",
      ],
      price: 49.99,
      brand: "Chapter & Verse",
      brandAr: "تشابتر آند فيرس",
      rating: 4.7,
      numReviews: 26,
      stock: 12,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Chapter & Verse Cozy Reading Set",
      nameAr: "طقم تشابتر آند فيرس للقراءة الدافئة",
      slug: "chapter-verse-cozy-reading-set",
      category: "Books",
      categoryAr: "كتب",
      description: "A favorite novel paired with a reading nook essential.",
      descriptionAr: "رواية مفضلة برفقة أساسيات ركن القراءة.",
      images: [
        "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c",
        "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c",
      ],
      price: 34.0,
      brand: "Chapter & Verse",
      brandAr: "تشابتر آند فيرس",
      rating: 4.4,
      numReviews: 10,
      stock: 15,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Chapter & Verse Coffee Table Collection",
      nameAr: "مجموعة تشابتر آند فيرس لطاولة القهوة",
      slug: "chapter-verse-coffee-table-collection",
      category: "Books",
      categoryAr: "كتب",
      description: "Beautifully illustrated hardcovers made for display and browsing.",
      descriptionAr: "كتب مجلدة مصورة بعناية مثالية للعرض والتصفح.",
      images: [
        "https://images.unsplash.com/photo-1512820790803-83ca734da794",
        "https://images.unsplash.com/photo-1495446815901-a7297e633e8d",
      ],
      price: 59.0,
      brand: "Chapter & Verse",
      brandAr: "تشابتر آند فيرس",
      rating: 4.2,
      numReviews: 5,
      stock: 9,
      isFeatured: false,
      banner: null,
    },
    // Accessories
    {
      name: "Aster Minimalist Analog Watch Duo",
      nameAr: "طقم أستر لساعتين أنالوج بسيطتين",
      slug: "aster-minimalist-analog-watch-duo",
      category: "Accessories",
      categoryAr: "إكسسوارات",
      description: "Two matching analog watches with a clean, minimalist face.",
      descriptionAr: "ساعتان أنالوج متطابقتان بتصميم بسيط وأنيق.",
      images: [
        "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
        "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
      ],
      price: 84.0,
      brand: "Aster",
      brandAr: "أستر",
      rating: 4.5,
      numReviews: 18,
      stock: 14,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Wanderer Everyday Backpack",
      nameAr: "حقيبة واندرر اليومية",
      slug: "wanderer-everyday-backpack",
      category: "Accessories",
      categoryAr: "إكسسوارات",
      description: "A durable, spacious backpack built for daily commutes and weekend trips.",
      descriptionAr: "حقيبة ظهر متينة وواسعة مناسبة للتنقل اليومي ورحلات نهاية الأسبوع.",
      images: [
        "https://images.unsplash.com/photo-1553062407-98eeb64c6a62",
        "https://images.unsplash.com/photo-1491637639811-60e2756cc1c7",
      ],
      price: 69.99,
      brand: "Wanderer Co.",
      brandAr: "واندرر",
      rating: 4.6,
      numReviews: 23,
      stock: 20,
      isFeatured: true,
      banner: null,
    },
    {
      name: "Aster Structured Leather Handbag",
      nameAr: "حقيبة يد أستر الجلدية",
      slug: "aster-structured-leather-handbag",
      category: "Accessories",
      categoryAr: "إكسسوارات",
      description: "A structured handbag crafted from genuine leather for a polished finish.",
      descriptionAr: "حقيبة يد ذات تصميم أنيق مصنوعة من الجلد الطبيعي.",
      images: [
        "https://images.unsplash.com/photo-1584917865442-de89df76afd3",
        "https://images.unsplash.com/photo-1584917865442-de89df76afd3",
      ],
      price: 119.0,
      brand: "Aster",
      brandAr: "أستر",
      rating: 4.3,
      numReviews: 9,
      stock: 7,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
